[package]
name = "primes-cli"
version = "0.1.2"
authors = ["Sean Macdonald <sean@crazyhorsecoding.com>"]
edition = "2018"
description = "A command-line utility for finding prime numbers"

[[bin]]
name = "primes"
path = "src/main.rs"

[dependencies]
primes = "0.2.*"
clap = "2"